site_name: Tom's Recipe Book
repo_url: https://github.com/tom-davies/recipe-book
repo_name: tom-davies/recipe-book

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: green
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
  icon:
    logo: material/food
    admonition:
      tip: material/leaf
  font:
    text: Fira Sans
    code: Fira Code

plugins:
  - search

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.smartsymbols
  - pymdownx.details
  - attr_list
  - admonition

extra_css:
  - extra.css